#Specifies the year to fake (0 = disable)
fakeYear = 2026
#Specifies the month to fake (0 = disable, 1 = January, 2 = February, ...)
fakeMonth = 3
#Specifies the day to fake (0 = disable)
fakeDayOfMonth = 30
#Only fake date when queried by specified mods
#Use * to allow any (not recommended)
filter = ["supplementaries"]
#When enabled, prints verbose information when faking date
debugFakingDate = false
#When enabled, prints verbose information when not faking date (mod not in filter)
debugNonFakingDate = false
